version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DB_DSN=postgresql://user:password@db:5432/rag_db
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:80"
    env_file:
      - .env

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rag_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: